# Notebook für Review "Historisiertes Gemeindeverzeichnis"

## Install/Import Modules

In [1]:
%pip install -q ipycytoscape networkx
import ipycytoscape as cy
import networkx as nx
import pandas as pd
from ext.sparql import query, display_result

# Datenmodell

## version.link

Die Daten zu den Gemeinden sind gemäss dem Schema https://version.link transformiert und in den Namespaces ld.admin.ch/municipality/ resp. ld.admin.ch/municipality/version/ zu finden.

## register.ld.admin.ch/agvch

Die Ursprungsdaten zum historisierten Gemeindeverzeichnis werden vom BFS als [eCH-0071 Standard](https://www.ech.ch/de/ech/ech-0071/1.1-0) gepflegt. Als direkte Linked Data Konversion existieren die Daten im Namespace register.ld.admin.ch/agvch/municipality/ resp. register.ld.admin.ch/agvch/municipalityversion/.

# vl:Identity 

## Beispiel aktuelle Gemeinde (Bern)

In [2]:
df = await query("""

PREFIX vl: <https://version.link/>

SELECT * 
FROM <https://lindas.admin.ch/territorial>
WHERE {

    <https://ld.admin.ch/municipality/351> ?p ?o.

}


""", "https://test.lindas.admin.ch/query")

display_result(df)

Die Mandatory Properties aus version.link für eine Identität sind:

- OK: rdf:type vl:Identity
- OK: vl:version
- OK: vl:inVersionedIdentitySet
- OK: schema:identifier

Gemeinde unter register.ld.admin.ch/agvch/municipality/

In [3]:
df = await query("""

PREFIX vl: <https://version.link/>

SELECT * 
FROM <https://lindas.admin.ch/territorial>
WHERE {

    <https://register.ld.admin.ch/agvch/municipality/351> ?p ?o.

}


""", "https://test.lindas.admin.ch/query")

display_result(df)

## Beispiel nicht mehr existierende Gemeinde (Ennenda)

In [4]:
df = await query("""

PREFIX vl: <https://version.link/>
PREFIX admin: <https://schema.ld.admin.ch/>

SELECT * 
FROM <https://lindas.admin.ch/territorial>
WHERE {

    <https://ld.admin.ch/municipality/1607> ?p ?o.
}


""", "https://test.lindas.admin.ch/query")

display_result(df)

Die Mandatory Properties aus version.link für eine nicht mehr existierende Identität sind:

- OK: rdf:type vl:Identity
- OK: vl:version
- OK: vl:inVersionedIdentitySet
- OK: schema:identifier
- OK: vl:Deprecated

--> Frage: Für was ist das schema:DefinedTermSet https://ld.admin.ch/dimension/municipality notwendig? Wohl für visualize.admin.ch - aber gehören da vl:Deprecated auch rein?

## Hinweis zu vl:Deprecated

version.link lässt offen, dass man aktiven Gemeinden bspw. admin:Municipality und nicht mehr aktiven admin:AbolishedMunicipality zuweist (und kein admin:Municipality mehr), somit könnte man einfacher nach allen aktiven suchen. Der Grund wieso ein vl:Deprecated eingeführt wurde, ist vor allem für die Versionen: Das Prinzip dort ist, dass man nichts ändern will, was man mal hinzugefügt hat, man will also nicht, dass bspw. ein vl:ActiveVersion durch ein vl:DeprecatedVersion ersetzt wird, dieser Graph ist "strictly growing", man muss also ein vl:Deprecated hinzutun, ohne etwas wegzunehmen. Damit bei den Identities der gleiche Mechanismus spielt, ist es dort auch so, aber in der Praxis könnte man immer zusätzlich zu vl:Identity als Typ auch etwas setzen, das man dann wenn die Identität abolished wird, weglässt und durch ein Spezifikum ersetzt, also bspw. admin:PoliticalMunicipality durch admin:AbolishedPoliticalMunicipality

## Anzahl aller Gemeinden

In [5]:
df = await query("""

PREFIX vl: <https://version.link/>
PREFIX admin: <https://schema.ld.admin.ch/>

SELECT (COUNT(*) AS ?count)
FROM <https://lindas.admin.ch/territorial>
WHERE {

    ?muni a admin:PoliticalMunicipality.

}
""", "https://test.lindas.admin.ch/query")

display_result(df)

## Anzahl aller nicht mehr aktiven Gemeinden

In [6]:
df = await query("""

PREFIX vl: <https://version.link/>
PREFIX admin: <https://schema.ld.admin.ch/>

SELECT (COUNT(*) AS ?count)
FROM <https://lindas.admin.ch/territorial>
WHERE {

    ?muni a admin:PoliticalMunicipality;
        a vl:Deprecated.

}
""", "https://test.lindas.admin.ch/query")

display_result(df)

## Anzahl aller aktiver Gemeinden

In [7]:
df = await query("""

PREFIX vl: <https://version.link/>
PREFIX admin: <https://schema.ld.admin.ch/>

SELECT (COUNT(*) AS ?count)
FROM <https://lindas.admin.ch/territorial>
WHERE {

    ?muni a admin:PoliticalMunicipality;
    
    FILTER NOT EXISTS {?muni a vl:Deprecated}
    #MINUS {?muni a vl:Deprecated}

}
""", "https://test.lindas.admin.ch/query")

display_result(df)

# vl:Version

## Beispiel für eine Version (Ennenda)

In [8]:
df = await query("""

PREFIX vl: <https://version.link/>
PREFIX admin: <https://schema.ld.admin.ch/>

SELECT * 
FROM <https://lindas.admin.ch/territorial>
WHERE {

    <https://ld.admin.ch/municipality/version/12279> ?p ?o.
}


""", "https://test.lindas.admin.ch/query")

display_result(df)

Die Mandatory Properties aus version.link für eine Version sind:

- OK: rdf:type vl:Version
- OK: vl:identity
- OK: vl:identityIdentifier
- **NOK**: vl:inVersionedIdentitySet
- OK: schema:identifier
- OK: vl:successor

Version unter register.ld.admin.ch/agvch/municipalityversion/

In [9]:
df = await query("""

PREFIX vl: <https://version.link/>
PREFIX admin: <https://schema.ld.admin.ch/>

SELECT * 
FROM <https://lindas.admin.ch/territorial>
WHERE {

    <https://register.ld.admin.ch/agvch/municipalityversion/12279> ?p ?o.
}


""", "https://test.lindas.admin.ch/query")

display_result(df)

# Veränderungsprozesse

## Beispiel für Versionsgeschichte Fusion (Klosters)

Welche Gemeinden spielten alle eine Rolle bei der heutigen Gemeinde "Klosters" (BFS Nummer 3871)?

In [10]:
df = await query("""

PREFIX vl: <https://version.link/>
PREFIX admin: <https://schema.ld.admin.ch/>
PREFIX schema: <http://schema.org/>

SELECT ?participants ?name
FROM <https://lindas.admin.ch/territorial>
WHERE {

    <https://ld.admin.ch/municipality/3871> vl:version ?final.
    ?participants vl:successor* ?final;
        schema:name ?name.
    
    MINUS {?participants a vl:ChangeEvent}
}


""", "https://test.lindas.admin.ch/query")

display_result(df)

Grafische Darstellung

In [11]:
df = await query("""

PREFIX vl: <https://version.link/>
PREFIX admin: <https://schema.ld.admin.ch/>
PREFIX schema: <http://schema.org/>

SELECT ?source ?target
FROM <https://lindas.admin.ch/territorial>
WHERE {

    <https://ld.admin.ch/municipality/3871> vl:version ?final.
    ?source vl:successor* ?final;
        vl:successor ?target.
    
    MINUS {?source a vl:ChangeEvent}
}


""", "https://test.lindas.admin.ch/query")


G = nx.from_pandas_edgelist(df, create_using=nx.DiGraph())

my_style = [
    {
        'selector': 'node',
         'style': {
            'font-family': 'helvetica',
            'font-size': '8px',
            'label': 'data(id)'
         }
    },
    {
        "selector": "edge.directed",
        "style": {
            "curve-style": "bezier",
            "target-arrow-shape": "triangle",
        }
    }
]

muni = cy.CytoscapeWidget()
muni.graph.add_graph_from_networkx(G, directed=True)
muni.set_style(my_style)
muni.set_layout(name = "dagre", rankDir = "LR")
muni

CytoscapeWidget(cytoscape_layout={'name': 'dagre', 'rankDir': 'LR'}, cytoscape_style=[{'selector': 'node', 'st…

## Beispiel für Versionsgeschichte Teilung (Bolligen)

Für Bolligen (BFS Nummer 352) als Beispiel für eine Gemeinde, die sich geteilt hat:

In [12]:
df = await query("""

PREFIX vl: <https://version.link/>
PREFIX admin: <https://schema.ld.admin.ch/>
PREFIX schema: <http://schema.org/>

SELECT ?source ?target
FROM <https://lindas.admin.ch/territorial>
WHERE {

    <https://ld.admin.ch/municipality/352> vl:version ?final.
    ?source vl:successor* ?final;
        vl:successor ?target;
        schema:name ?sourceName.
    ?target schema:name ?targetName.
    
    MINUS {?source a vl:ChangeEvent}
}


""", "https://test.lindas.admin.ch/query")


G = nx.from_pandas_edgelist(df, source="source", target="target", create_using=nx.DiGraph())

my_style = [
    {
        'selector': 'node',
         'style': {
            'font-family': 'helvetica',
            'font-size': '8px',
            'label': 'data(id)'
         }
    },
    {
        "selector": "edge.directed",
        "style": {
            "curve-style": "bezier",
            "target-arrow-shape": "triangle",
        }
    }
]

muni = cy.CytoscapeWidget()
muni.graph.add_graph_from_networkx(G, directed=True)
muni.set_style(my_style)
muni.set_layout(name = "dagre", rankDir = "LR")
muni

CytoscapeWidget(cytoscape_layout={'name': 'dagre', 'rankDir': 'LR'}, cytoscape_style=[{'selector': 'node', 'st…

## Alle Gemeinden, die sich geteilt haben

In [13]:
df = await query("""

PREFIX vl: <https://version.link/>
PREFIX admin: <https://schema.ld.admin.ch/>
PREFIX schema: <http://schema.org/>

SELECT * 
FROM <https://lindas.admin.ch/territorial>
WHERE {
    
    ?source schema:name ?name
    
    {
        SELECT ?source (COUNT(?target) as ?successors)
        WHERE {

            ?source vl:successor ?target;

            MINUS {?source a vl:ChangeEvent}
        } 
        GROUP BY ?source
    }
    FILTER(?successors > 1)
}

""", "https://test.lindas.admin.ch/query")

display_result(df)

## Analyse Berg (TG)

Dies ist ein Beispiel für eine Abfrage, wo zu Beginn oder am Ende nicht eine einzelne Version steht, sondern man von einer Version in der "Mitte" des Geschehens ausgeht. Zusätzlich sollen nicht mehr nur die URI der Versionen in der Grafik angezeigt werden, sondern die Namen, dafür muss man Node Attribute generieren (man kann nicht einfach nur auf die Namen setzten, weil die sind ja nicht eindeutig).

In [14]:
edge_df = await query("""

PREFIX vl: <https://version.link/>
PREFIX admin: <https://schema.ld.admin.ch/>
PREFIX schema: <http://schema.org/>

SELECT ?source ?target ?sourceName ?targetName
FROM <https://lindas.admin.ch/territorial>
WHERE {
    
    {
        <https://ld.admin.ch/municipality/version/14062> vl:predecessor* ?target.
        ?target vl:predecessor ?source;
            schema:name ?targetName.
        ?source schema:name ?sourceName.
    }
    UNION
    {
        <https://ld.admin.ch/municipality/version/14062> vl:successor* ?source.
        ?source vl:successor ?target;
            schema:name ?sourceName.
        ?target schema:name ?targetName.
    }
}

""", "https://test.lindas.admin.ch/query")

ids = pd.Series.tolist(edge_df["source"]) + pd.Series.tolist(edge_df["target"])
names = pd.Series.tolist(edge_df["sourceName"]) + pd.Series.tolist(edge_df["targetName"])

node_df = pd.DataFrame(list(zip(ids, names)), columns = ["id", "name"])
node_df.drop_duplicates(inplace=True)

G = nx.from_pandas_edgelist(edge_df, source="source", target="target", create_using=nx.DiGraph())
nx.set_node_attributes(G, node_df.set_index('id').to_dict('index'))


my_style = [
    {
        'selector': 'node',
         'style': {
            'font-family': 'helvetica',
            'font-size': '8px',
            'label': 'data(name)'
         }
    },
    {
        "selector": "edge.directed",
        "style": {
            "curve-style": "bezier",
            "target-arrow-shape": "triangle",
        }
    }
]

muni = cy.CytoscapeWidget()
muni.graph.add_graph_from_networkx(G, directed=True)
muni.set_style(my_style)
muni.set_layout(name = "dagre", rankDir = "LR")
muni

CytoscapeWidget(cytoscape_layout={'name': 'dagre', 'rankDir': 'LR'}, cytoscape_style=[{'selector': 'node', 'st…

# vl:ChangeEvent

## Beispiel Change Event

In [15]:
df = await query("""

PREFIX vl: <https://version.link/>
PREFIX admin: <https://schema.ld.admin.ch/>
PREFIX schema: <http://schema.org/>

SELECT *
FROM <https://lindas.admin.ch/territorial>
WHERE {

    <https://ld.admin.ch/municipality/changeevent/3953> ?p ?o.
}


""", "https://test.lindas.admin.ch/query")

display_result(df)

Problem: Es ist schwierig rauszufinden, welcher Change Typ ein ChangeEvent aufweist, weil das alles als rdf:type ausgeführt ist. Gemäss version.link sollte der Change Typ ja eine Subklasse von vl:ChangeEvent sein, aber wie kann man das in LINDAS abfragen?

Wäre es allenfalls sinnvoller, den Change Typ mit vl:changeEventType an den vl:ChangeEvent anzuhängen?

## Abfrage Change Typ 

Welchen Change Typ hat ein bestimmtes vl:ChangeEvent (ohne die anderen Klassen mitzuhaben):

In [16]:
df = await query("""

PREFIX vl: <https://version.link/>
PREFIX admin: <https://schema.ld.admin.ch/>
PREFIX schema: <http://schema.org/>

SELECT *
FROM <https://lindas.admin.ch/territorial>
WHERE {

    <https://ld.admin.ch/municipality/changeevent/3953> a ?type.
    
    FILTER(?type != vl:ChangeEvent)
    FILTER(?type != admin:MunicipalityChangeEvent)
    FILTER(?type != <https://ld.admin.ch/ech/71/MunicipalityChangeEvent>)
}


""", "https://test.lindas.admin.ch/query")

display_result(df)

## Verwendete Change Typen

In [17]:
df = await query("""

PREFIX vl: <https://version.link/>
PREFIX admin: <https://schema.ld.admin.ch/>
PREFIX schema: <http://schema.org/>

SELECT ?type (COUNT(?change) as ?count)
FROM <https://lindas.admin.ch/territorial>
WHERE {

    ?change a vl:ChangeEvent;
        a ?type.
    
    FILTER(?type != vl:ChangeEvent)
    FILTER(?type != admin:MunicipalityChangeEvent)
    FILTER(?type != <https://ld.admin.ch/ech/71/MunicipalityChangeEvent>)
} GROUP BY ?type 


""", "https://test.lindas.admin.ch/query")

display_result(df)

Wo sind die vl:Combination etc.?

## Art der Changes (Beispiel Klosters)

Jetzt soll nicht nur der Successor resp. der Predecessor einer Version eine Rolle spielen, sondern der Prozess, der zu dieser Version geführt hat:

In [18]:
df = await query("""

PREFIX vl: <https://version.link/>
PREFIX admin: <https://schema.ld.admin.ch/>
PREFIX schema: <http://schema.org/>

SELECT ?predecessor ?changeEvent ?type ?successor
FROM <https://lindas.admin.ch/territorial>
WHERE {

    <https://ld.admin.ch/municipality/3871> vl:version ?final.
    ?predecessor vl:successor* ?final;
        vl:successor ?successor;
        vl:endEvent ?changeEvent.

    ?changeEvent a ?type.
    
    #FILTER(?type != vl:ChangeEvent)
    #FILTER(?type != admin:MunicipalityChangeEvent)
    #FILTER(?type != <https://ld.admin.ch/ech/71/MunicipalityChangeEvent>)
    
    

} ORDER BY ?predecessor


""", "https://test.lindas.admin.ch/query")

display_result(df)

Problem: vl:ChangeEvent 3450 hat kein Change Typ, müsste vl:Combination sein

# Verschachtelte vl:ChangeEvent

Der Abschnitt https://version.link/#ChangeEvent ist wohl noch zu wenig ausführlich geschrieben. Hier ein Beispiel, wenn man zwei Gemeinden fusionieren lässt, wobei es für die eine Gemeinde eine Aufhebung ist, für die andere eine Gebietsänderung (kleine Gemeinde fusioniert in grosse):

Es sind also drei Versionen beteiligt:

- VersionKleinVorher
- VersionGrossVorher
- VersionGrossNachher

Weiter sind auch drei Changes beteiligt:

- vl:Combination
- Abolishment (nicht in version.link definiert)
- Reshape (nicht in version.link definiert)

Der Event vl:Combination verbindet als vl:endEvent die Versionen *VersionKleinVorher* und *VersionGrossVorher* über vl:startEvent mit der Version *VersionGrossNachher*.

Der Event Abolishment verbindet nur die Versionen *VersionKleinVorher* mit *VersionGrossNachher und der Event Reshape nur *VersionGrossVorher* mit *VersionGrossNachher*.

Frage: Würde man das evt. nicht besser als irgendwie vl:SubChangeEvent innerhalb des vl:Combination abhandeln, weil sonst hat man das Problem, dass *VersionKleinVorher* drei vl:successor hat: *VersionGrossNachher*, vl:Combination und Abolishment, aber vielleicht muss das historisierte Gemeindeverzeichnis gar nicht so weit gehen, weil die Details hätte man ja dann noch im register.ld.admin.ch/agvh/municipalityversion...