# Notebook für Review "Historisiertes Gemeindeverzeichnis"

In [1]:
import pandas as pd
from ext.sparql import query, display_result

## vl:Identity 

### Aktuelle Gemeinde (Bern)

In [2]:
df = await query("""

PREFIX vl: <https://version.link/>

SELECT * WHERE {

    <https://ld.admin.ch/municipality/351> ?p ?o.

}


""", "https://test.lindas.admin.ch/query")

display_result(df)

Die Mandatory Properties aus version.link für eine Identität sind:

- OK: rdf:type vl:Identity
- OK: vl:version
- **NOK**: vl:inVersionedIdentitySet
- OK schema:identifier

Gemeinde unter register.ld.admin.ch/agvch

In [3]:
df = await query("""

PREFIX vl: <https://version.link/>

SELECT * WHERE {

    <https://register.ld.admin.ch/agvch/municipality/351> ?p ?o.

}


""", "https://test.lindas.admin.ch/query")

display_result(df)

### Nicht mehr existierende Gemeinde (Ennenda)

In [4]:
df = await query("""

PREFIX vl: <https://version.link/>
PREFIX admin: <https://schema.ld.admin.ch/>

SELECT * WHERE {

    <https://ld.admin.ch/municipality/1607> ?p ?o.
}


""", "https://test.lindas.admin.ch/query")

display_result(df)

Die Mandatory Properties aus version.link für eine nicht mehr existierende Identität sind:

- **NOK**: rdf:type vl:Identity
- **NOK**: vl:version
- **NOK**: vl:inVersionedIdentitySet
- OK schema:identifier
- **NOK** vl:Deprecated

--> Hinweis: version.link lässt offen, dass man aktiven Gemeinden bspw. admin:Municipality und nicht mehr aktiven admin:AbolishedMunicipality zuweist (und kein admin:Municipality mehr), somit könnte man einfacher nach allen aktiven suchen.

## vl:Version

### ld.admin.ch/municipality/version

In [5]:
df = await query("""

PREFIX vl: <https://version.link/>
PREFIX admin: <https://schema.ld.admin.ch/>

SELECT * WHERE {

    <https://ld.admin.ch/municipality/version/12279> ?p ?o.
}


""", "https://test.lindas.admin.ch/query")

display_result(df)

### register.ld.admin.ch/agvch/municipalityversion

In [6]:
df = await query("""

PREFIX vl: <https://version.link/>
PREFIX admin: <https://schema.ld.admin.ch/>

SELECT * WHERE {

    <https://register.ld.admin.ch/agvch/municipalityversion/12279> ?p ?o.
}


""", "https://test.lindas.admin.ch/query")

display_result(df)