In [48]:
import pandas as pd
import geopandas as gpd
import numpy as np
from ext.sparql import query, display_result

In [49]:
%pip install -q folium
import folium

In [5]:
df = await query("""

SELECT * WHERE {

    <https://lod.opentransportdata.swiss/relation/8587933/8587940/vbg/bus/regular> ?p ?o.

}

""")

display_result(df)

In [85]:
df = await query("""

PREFIX schema: <http://schema.org/>

SELECT * WHERE {

    ?station a <http://vocab.gtfs.org/terms#Station>;
        schema:name "Tschamerie".

}

""")

display_result(df)

In [21]:
df = await query("""

PREFIX schema: <http://schema.org/>

SELECT * WHERE {

    ?relation a <https://lod.opentransportdata.swiss/vocab/Relation>;
        <http://vocab.gtfs.org/terms#stop> <https://lod.opentransportdata.swiss/didok/8508265>;
        <http://vocab.gtfs.org/terms#stop> ?stop.
    ?stop schema:name ?name.
    
    FILTER (?name != "Hasle-Rüegsau")

} LIMIT 100

""")

display_result(df)

In [77]:
df = await query("""

PREFIX schema: <http://schema.org/>

SELECT DISTINCT ?name ?geometry ?ele WHERE {
    
    ?relation <http://vocab.gtfs.org/terms#stop> ?stop.
    ?stop schema:name ?name;
        <http://www.opengis.net/ont/geosparql#hasGeometry>/<http://www.opengis.net/ont/geosparql#asWKT> ?geometry;
        schema:elevation ?ele.
    
    {
        SELECT ?relation (COUNT(?id) as ?number) WHERE {

            { 

                SELECT DISTINCT * WHERE {

                    ?relation a <https://lod.opentransportdata.swiss/vocab/Relation>;
                        <https://lod.opentransportdata.swiss/vocab/zone> <https://lod.opentransportdata.swiss/zone/libero/libero-billett-libero/101>;
                        <https://lod.opentransportdata.swiss/vocab/zone>/schema:identifier ?id.

                }
            }

        } GROUP BY ?relation
    }
    FILTER(?number = 1)
    
}
    
""")

display_result(df)

In [78]:
df = gpd.GeoDataFrame(df)

df["geometry"] = gpd.GeoSeries.from_wkt(df["geometry"], crs="EPSG:4326")

df['lat'] = df.geometry.y
df['long'] = df.geometry.x

sw = df.bounds[["miny", "minx"]].min().values.tolist()
ne = df.bounds[["maxy", "maxx"]].max().values.tolist()

display(df.head())

,name,geometry,ele,lat,long
0,"Liebefeld, Hessstrasse",POINT (7.42266 46.93235),563.0,46.932354,7.422665
1,"Liebefeld, Neumattweg",POINT (7.41527 46.93408),560.0,46.934079,7.415271
2,"Liebefeld, Liebefeld Park",POINT (7.42064 46.93091),561.0,46.930914,7.420643
3,"Wabern, Weyergut",POINT (7.45734 46.92927),536.0,46.929268,7.457344
4,"Spiegel, Spiegel",POINT (7.43568 46.92657),565.0,46.926571,7.435679

In [80]:
# create the map and center it around the mean coordinates of the stations
m = folium.Map(location=[df['lat'].mean(),df['long'].mean()], tiles="openstreetmap", zoom_start=8)

# add marker one by one on the map
for i in range(0,len(df)):
    folium.Marker(
        location=[df.iloc[i]['lat'], df.iloc[i]['long']],
        popup=folium.Popup(folium.Html('<h3>' + df.iloc[i]['name'] + '</h3>', script=True), max_width=500),
        icon=folium.Icon(icon='train', prefix='fa')
   ).add_to(m)

m.fit_bounds([sw, ne])
# show the map
m

## Verbindungen mit über mehrere Relationen

In [83]:
df = await query("""

PREFIX schema: <http://schema.org/>

SELECT * WHERE {

    BIND(<https://lod.opentransportdata.swiss/didok/8589069> as ?start)

    ?start (^<http://vocab.gtfs.org/terms#stop>/<http://vocab.gtfs.org/terms#stop>)* ?stop.
    

} LIMIT 100

""")

display_result(df)