<br>

<img src="https://www.fedlex.admin.ch/assets/pictos/logo-ch.png" style="width:15%; float:right">

# Tutorial Staatskalender
**Version vom 30.08.2023 - Work in Progress**

Dieses Notebook dient dazu, den Staatskalender in RDF/Linked Data besser zu verstehen, um die Daten kompetent nutzen zu können. Es ist **keine Einführung** - weder in Linked Data noch in SPARQL. Wer die technischen Informationen und Voraussetzungen zu Beginn überspringen möchte, kann direkt zum eigentlichen [Tutorial](#Tutorial) springen.

## Interaktives Notebook

Dieses Tutorial ist ein sogenanntes **interaktives JupyterLite Notebook**. In diesem Notebook können Sie den Inhalt der einzelnen Zellen interaktiv ändern und diese Zellen direkt ausführen, um das Ergebnis Ihrer Änderungen sofort zu sehen. Die Zellen enthalten entweder [Markdown](https://en.wikipedia.org/wiki/Markdown)-Inhalt (wie diese Zelle) oder ausführbaren Python-Quellcode. Dies ist für ein Tutorial sehr hilfreich, weil Inhalte beliebig mit ausführbarem Quellcode kombiniert werden können. Es können also Abfragen gezeigt werden, diese erklärt werden und darauf weiter aufgebaut werden.

**Um direkt loslegen zu können klicken Sie oben im Menu auf Run -> Run All Cells.**  
**Einzelne ausgewählte Zellen können sie danach abändern und mit dem "Play-Button" erneut ausführen und so Abfragen individuell anpassen.**

Das Notebook startet mit einem [Setup](#Setup) der Programierumgebung. Das eigentliche Tutorial startet [hier](#Tutorial).

*Zusätzliche Informationen zu JupyterLite:*  
JupyterLite is ein spezielles Jupyter Notebook mit dem Vorteil, vollständig browserbasiert zu sein, ohne eine aufwändige Backend-Infrastruktur zu benötigen. Der Nachteil ist, dass die erstmalige Ausführung der Zellen einige Zeit in Anspruch nehmen kann, weil eine erhebliche Menge von Daten geladen werden muss. Dass eine Zelle noch in Ausführung ist, ist am `[*]` links neben der Zelle erkennbar. Nach Abschluss der Ausführung erscheint statt eines `*` eine Zahl. Vor der ersten Ausführung ist eine leere Klammer `[ ]` zu sehen. Nachfolgende wiederholte Ausführungen von Zellen werden aufgrund der gespeicherten Daten in Ihrem Browser-Cache viel schneller sein. Wenn Sie Änderungen am Tutorial vornehmen, werden diese Änderungen automatisch lokal im Browser-Cache gespeichert. Bei einem darauffolgenden Öffnen werden wiederum die Änderungen aus dem Browser-Cache geladen. Um wieder zur Ursprüngsversion des Tutorials zurückzukehren, müssen entweder die Browser-Daten gelöscht werden, oder Sie öffnen das Tutorial in einem Chrome-Inkognito Fenster, wo die Änderungen nach Schliessen des Fensters aus dem Cache gelöscht werden.

Wenn Sie mehr über die Handhabung von Jupyter Notebooks wissen wollen, finden Sie hier zwei nützliche Ressourcen:

- [Die JupyterLab Interface](https://jupyterlab.readthedocs.io/en/stable/user/interface.html)
- [Das Jupyter Notebook](https://jupyterlab.readthedocs.io/en/stable/user/notebook.html)

## Setup

Eine SPARQL Abfrage ist nichts anderes als ein POST-Request an den entsprechenden Triple Store Datenbank Server. Um diese Requests und die erhaltenen Antworten einfacher handhaben zu können, enthält dieses Notebook vorbereiteten Python Code, der nachfolgend importiert wird. Zusätzlich wird das `pandas` Modul importiert, welches die Möglichkeit bietet, die tabellarischen Daten der SPARQL Abfragen als [Pandas Dataframes](https://pandas.pydata.org/docs/index.html) weiter zu verarbeiten.

In [1]:
%pip install -q ipywidgets==8.0.4 ipycytoscape networkx nbformat
import ipycytoscape as cy
import networkx as nx
import pandas as pd
from ext.sparql import query, display_result

# Tutorial

Der Staatskalender ist eine Art "Organigramm" der Bundesbehörden. Da dieses Organigramm einer gewissen Dynamik unterworfen ist (Behörden ändern ihren Namen oder werden mit anderen Behörden zusammengelegt, etc.), ist der Staatskalender in RDF/Linked Data gemäss dem unter https://version.link beschriebenen Datenmodell erstellt. Dieses Datenmodell soll im nachfolgenden Teil erkundet werden.

## Versioned Identity Set

Um alle Behörden in eine gemeinsame Menge zu gruppieren, werden sie gemäss [version.link](https://version.link) mit Hilfe des Attributs [`vl:inVersionedIdentitySet`](https://version.link/#inVersionedIdentitySet) dem Set `<https://ld.admin.ch/ou>` zugeteilt.

## Identitäten und Versionen

Daten gemäss [version.link](https://version.link) werden als Identitäten und Versionen modelliert. Die Identität ist dabei quasi die unabänderliche Existenz einer Behörde und die Versionen sind die zeitlichen Änderungen der Behörden. Jede Identität besteht dabei aus einer Abfolge von mindestens einer Version und die Informationen der Identität beruhen auf der letzten Version.

Anders ausgedrück beschreiben die Identitäten den **Ist-Zustand** und die Versionen die **historische Entwicklung**. Der Ist-Zustand wird dabei auch als Identity-Graph und die historische Entwicklung als Version-Graph bezeichnet.

## Aktuelle Behörden und ihr jeweiliger Name

Um eine Liste aller aktuellen Behörden zu erhalten, muss nach der Klasse [`vl:Identity`](https://version.link/#Identity) gesucht werden und diese Entitäten müssen im entsprechenden Versioned Identity Set sein:

In [2]:
df = await query("""

PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX vl: <https://version.link/>

SELECT DISTINCT * WHERE {

    ?org a vl:Identity;
        vl:inVersionedIdentitySet <https://ld.admin.ch/ou>;
        schema:name ?name.
        
    FILTER(lang(?name) = 'de')
}

LIMIT 10

""")

display_result(df)

## Anzahl aktueller Behörden

Die aktuelle Anzahl aller Behörden im Staatskalender kann folgendermassen ermittelt werden:

In [3]:
df = await query("""

PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX vl: <https://version.link/>

SELECT (COUNT(?org) as ?number) WHERE {

    ?org a vl:Identity;
        vl:inVersionedIdentitySet <https://ld.admin.ch/ou>.
        
    FILTER NOT EXISTS {?org a vl:Deprecated.}

}

""")

display_result(df)

## Behörden, die so nicht mehr existieren

Behörden, die aufhören, zu existieren, werden nicht einfach gelöscht (auch deren Identität nicht), sondern erhalten zusätzlich die Klasse [`vl:Deprecated`](https://version.link/#Deprecated) zugewiesen:

In [4]:
df = await query("""

PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX vl: <https://version.link/>

SELECT * WHERE {

    ?org a vl:Identity;
        vl:inVersionedIdentitySet <https://ld.admin.ch/ou>;
        schema:name ?name;
        a vl:Deprecated.
        
    FILTER(lang(?name) = 'de')
} 

LIMIT 20

""")

display_result(df)

## Behörden mit einer "langen" Versionsgeschichte

Folgende Behörden haben eine Versionsgeschichte mit mehr als 5 Versionen:

In [5]:
df = await query("""

PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX vl: <https://version.link/>

SELECT ?id ?name ?versions WHERE {
    
    ?id schema:name ?name.
    
    FILTER(lang(?name) = 'de')
    FILTER(?number > 5)
        
    {
    SELECT ?id (GROUP_CONCAT(?version; separator=" ← ") AS ?versions) (COUNT(?version) AS ?number) WHERE {

      ?version a vl:Version;
          vl:identity ?id.

    } 
    GROUP BY ?id
    }
}

ORDER BY DESC(?number)

""")

display_result(df)

## "Wiederauferstandene" Behörden

Die nachfolgenden Versionen haben vl:successor mit schema:startDate > als schema:endDate der Version, es existiert also eine zeitliche Lücke, in der die Behörde "pausiert" hat.

In [6]:
df = await query("""

PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX vl: <https://version.link/>

SELECT * WHERE {

?version vl:successor ?succ;
    vl:inVersionedIdentitySet <https://ld.admin.ch/ou>;
    schema:endDate ?endDate.

?succ schema:startDate ?startDate.

BIND(day(?startDate - ?endDate) as ?diff)
FILTER(?diff > 0)

}
ORDER BY DESC(?diff)

LIMIT 10

""")

display_result(df)

## Behörden mit gleichen Namen

Folgendes Beispiel zeigt diejenigen Behörden, von denen mehrere mit gleichem Namen (an anderer Stelle im Organigramm) existieren. Dieses Beispiel zeigt, wie die von der SPARQL Query gelieferte Daten mit dem gesamten Spektrum der Datenverarbeitungsmöglichkeit von Python weiterverarbeitet werden kann:

In [7]:
df = await query("""

PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX vl: <https://version.link/>

SELECT * WHERE {

    ?identity a vl:Identity;
        schema:name ?name.
    
    FILTER(lang(?name) = 'de')

    FILTER NOT EXISTS {?identity a vl:Deprecated.}

}

ORDER BY ?name

""")

df['non_unique'] = df.duplicated(subset = 'name', keep = False)

df = df[df['non_unique'] == True]

display_result(df[["identity", "name"]].head(100))

## Behörden und ihr Pfad im Organigramm

Nachfolgende Query ermittelt alle Sub-Behörden einer frei wählbaren Behörde und zeigt den "Pfad" der entsprechenden Sub-Behörde an:

In [8]:
df = await query("""

PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX vl: <https://version.link/>

SELECT (GROUP_CONCAT(CONCAT(STR(?level), ":", STR(?parent_name)); separator= " → ") AS ?hierarchy) WHERE {

    BIND ('de' AS ?lang)

    ?parent schema:subOrganization* ?org.
    ?parent schema:name ?parent_name.
    FILTER(lang(?parent_name) = ?lang)

    {
    SELECT ?parent (COUNT(?org) AS ?level) WHERE {

        BIND (<https://ld.admin.ch/office/II.1.4> AS ?root) 
        
        #start root, e.g. <https://ld.admin.ch/FCh> = Bundeskanzlei
        #                 <https://ld.admin.ch/office/II.1.4> = Bundesarchiv

        ?root schema:subOrganization+ ?parent.
        ?org schema:subOrganization+ ?parent.


    } GROUP BY ?parent ORDER BY ?level
    }
} GROUP BY ?org ORDER BY ?hierarchy

""")

display_result(df)

## Behörden, die neu gegründet wurden

Folgende Query ermittelt die Behörden, die nach dem 1.1.2023 gegründet wurden:

In [9]:
df = await query("""

PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX vl: <https://version.link/>

SELECT ?org ?name ?date WHERE {

    ?org a vl:Identity;
        vl:version ?version;
        schema:name ?name.
        
    FILTER(lang(?name) = "de")
        
    OPTIONAL {?version vl:predecessor ?predecessor.}
    ?version schema:startDate ?date.
    
    FILTER(!BOUND(?predecessor))
    FILTER(?date > "2023-01-01")

} LIMIT 50

""")

display_result(df)

## Grafisches Organigramm

In [10]:
edge_df = await query("""

PREFIX vl: <https://version.link/>
PREFIX admin: <https://schema.ld.admin.ch/>
PREFIX schema: <http://schema.org/>

SELECT DISTINCT ?source ?sourceName ?target ?targetName
WHERE {

    BIND (<https://ld.admin.ch/office/VII.1.4> AS ?top)
   
    ?source schema:parentOrganization+ ?top;
        a vl:Identity;
        schema:parentOrganization ?target;
        schema:name ?sourceName.
        
    ?target schema:name ?targetName.
    
    FILTER(lang(?sourceName) = "de")
    FILTER(lang(?targetName) = "de")
}


""")

display_result(edge_df)

ids = pd.Series.tolist(edge_df["source"]) + pd.Series.tolist(edge_df["target"])
names = pd.Series.tolist(edge_df["sourceName"]) + pd.Series.tolist(edge_df["targetName"])

node_df = pd.DataFrame(list(zip(ids, names)), columns = ["id", "name"])
node_df.drop_duplicates(inplace=True)


G = nx.from_pandas_edgelist(edge_df, source="source", target="target", create_using=nx.DiGraph())
node_attributes = node_df.set_index('id').to_dict("index")
nx.set_node_attributes(G, node_attributes)


my_style = [
    {
        'selector': 'node',
         'style': {
            'font-family': 'helvetica',
            'font-size': '8px',
            'text-valign': "center",
             'text-wrap': 'wrap',
             'text-max-width': '50px',
             'width': '100px',
             'shape':'roundrectangle',
            'label': 'data(name)' #Zugriff auf das Attribut 'name' der Nodes
         }
    },
    {
        "selector": "edge.directed",
        "style": {
            "curve-style": "bezier",
            "target-arrow-shape": "triangle",
        }
    }
]

orga = cy.CytoscapeWidget()
orga.graph.add_graph_from_networkx(G, directed=True)
orga.set_style(my_style)
orga.set_layout(name = "dagre", rankDir = "BT")
orga

CytoscapeWidget(cytoscape_layout={'name': 'dagre', 'rankDir': 'BT'}, cytoscape_style=[{'selector': 'node', 'st…